### ISSUE TITLE
Lost Fish

### ISSUE THREAD

**Issue by uamv** [clarkwinkelmann/catch-the-fish#1] opened 2019-04-09 12:18 UTC
When fish are auto-placed, some of them get lost due to (1) byōbu private discussions and (2) restrictive tag permissions. It'd be nice to have the option to exclude such discussions or tags from the pond into which these fish are returned.

**Comment by clarkwinkelmann** [comment] 2019-05-27 13:17
Thanks for the report ! Sorry I completely missed the report, for some reason I wasn't watching my own repository :speak_no_evil: 

The first issue you report was supposed to be handled by the check for private discussions here

https://github.com/clarkwinkelmann/catch-the-fish/blob/59b09b2f946783096a571f982d51bc789cedc5c4/src/Repositories/Placement.php#L168

The second issue is not handled at all, it's true. I'm not sure how to handle it though. Restricted tags could be automatically excluded, but that can be a complex request to write to choose a discussion randomly. Or maybe by letting the creator of the fish round choose which tag will be used for the contest.

Can you confirm the first issue is indeed happening and that fishes end up in private discussions ? It shouldn't happen either manually or automatically. If so I'll try to come up with a fix for that.

**Comment by clarkwinkelmann** [comment] 2019-07-28 17:30
I'm closing this issue as I was not able to reproduce the issue with private discussions.

The tag restriction will be a "won't fix" for now, I don't plan to implement it.

Please let me know if you still encounter issues with private discussions :wink:

**Closed as completed by clarkwinkelmann** 2019-07-28 17:30 UTC
Labels: bug
